url: "https://alliedtesting.github.io/pgmex-blog"
baseurl: "/pgmex-blog"
title: PgMex Blog
subtitle: Allied Testing
description: PostgreSQL-Matlab connectivity
title-img: logo.png
title-url: "http://pgmex.alliedtesting.com"
subtitle-img: allied_logo.gif
subtitle-url: "https://www.alliedtesting.com"

# List of links in the navigation bar (excluding "Home" as well as those that are given as separate md files in the root folder)
navbar-links:
  Resources:
    - PgMex Library: "http://pgmex.alliedtesting.com"
    - Performance Tests: "https://github.com/AlliedTesting/pgmex-jdbc-perf-test"

excerpt_separator: <!--end_of_excerpt-->
excerpt_length: 200

google_analytics: "UA-47711680-3"

# gravatar:
#    hash: 
#    size: 80

# avatar: logo_small_sqr.png

disqus:
  shortname: "pgmexblog"
  show_comment_count: true
   
github:
  repo: https://github.com/AlliedTesting/pgmex-blog

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Allied Testing Ltd.
  email: "info@pgmex.alliedtesting.com"
  github: AlliedTesting/pgmex-blog    # eg. daattali
  url: https://www.alliedtesting.com
  
# Select which links to show in the footer
footer-links-active:
  mvp: false
  rss: true
  facebook: false
  email: true
  twitter: false
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "alliedtesting.github.io/pgmex-blog"  # eg. "deanattali.com/beautiful-jekyll"

# Output options (more information on Jekyll's site)
timezone: Europe/Moscow
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      nav-include: true  # include in header nav

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME